CREATE TABLE [dbo].[CAR](
	[REGNO] [nvarchar](50) NOT NULL,
	[MAKE] [nvarchar](50) NULL,
	[COLOUR] [nvarchar](25) NULL,
	[PRICE] [money] NULL,
	[OWNER] [nvarchar](50) NULL,
 CONSTRAINT [PK_CAR] PRIMARY KEY CLUSTERED 
(
	[REGNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAR]  WITH CHECK ADD  CONSTRAINT [FK_CAR_DRIVER] FOREIGN KEY([OWNER])
REFERENCES [dbo].[DRIVER] ([NAME])
ON UPDATE CASCADE
ON DELETE SET NULL
GO

ALTER TABLE [dbo].[CAR] CHECK CONSTRAINT [FK_CAR_DRIVER]