CREATE TABLE [dbo].[DRIVER](
	[NAME] [nvarchar](50) NOT NULL,
	[DOB] [date] NULL,
 CONSTRAINT [PK_DRIVER] PRIMARY KEY CLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]